[project]
name = "Agentic RAG PoC"
version = "0.1.0"
dependencies = [
    
]
requires-python = ">=3.12"
readme = "README.md"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"